---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 23.08.18 22:51
---

local RPD = require "scripts/lib/commonClasses"

local ai = require "scripts/lib/ai"

local storage = require "scripts/lib/storage"

local Process = require"scripts/lib/Process"

return ai.init{

    act       = function(me, ai, me)

if RPD.Dungeon.level:distance(RPD.Dungeon.hero:getPos(),me:getPos()) < 4 then 
h = true
else
h = false
end

if h then
me:beckon(RPD.Dungeon.hero:getPos())
else
me:getSprite():move(me:getPos(),Process.golden_gaurd_pos)
me:getSprite():idle()
me:move(Process.golden_gaurd_pos)
me:spend(1)
--me:beckon(Process.golden_gaurd_pos)
end
end,

    gotDamage = function(me, ai, me, src, dmg)
end,

    status = function(me, ai, me)
        return "атакует"
    end
}